name: Cache Example

on:
  workflow_dispatch:

jobs:
  npm-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Generate npm dependency cache key
        run: node src/index.js lock normalize --type npm --output tmp/cache/package-lock.deps.json

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('tmp/cache/package-lock.deps.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install
        run: npm ci
